server {
    listen 80;
    server_name pincheck.net www.pincheck.net;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name pincheck.net www.pincheck.net;

    ssl_certificate /etc/nginx/ssl/origin.crt;
    ssl_certificate_key /etc/nginx/ssl/origin.key;

    client_max_body_size 4M;

    location / {
        proxy_pass http://app:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
